### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by Studio384** [ChangeWindows/Viv#1]
Milestones are one of our 3 major pages (next to timeline and rings). As we rebuild the milestones feature, there are a few things we should take under consideration.

# Functionality
- [ ] Basic Milestones support
  - [ ] Milestones page with overview of all milestones
  - [ ] Overview of a milestones progress through its life cycle
  - [ ] Overview of current stable and preview build within that milestone
  - [ ] Show all builds of a platform within the given milestone
- [ ] Add milestone navigation to build pages

# URLs
### ` GET /milestones/`
Main public milestones page. Provides navigation to all milestone detail pages.

### `GET /milestones/<id>`
Milestone detail page where `id` is the codename of the milestone in lower case written as a string without spaces and other special characters (e.g. 'Redstone 5' becomes 'redstone5').

### `POST /milestones/`
Adds new milestone, will be accessible from the form on the Milestones-page.

### `PATCH /milestones/<id>`
Update an existing milestone where `id` is the codename of the milestone in lower case written as a string without spaces and other special characters (e.g. 'Redstone 5' becomes 'redstone5').

### `DELETE /milestones/<id>`
Delete a milestone where `id` is the codename of the milestone in lower case written as a string without spaces and other special characters (e.g. 'Redstone 5' becomes 'redstone5').

# Notes
We should consider adding an overview similar to the rings page but by milestone instead of by platform. The milestone detail pages would be fit for this.
