### ISSUE TITLE
Changelog UX

### ISSUE THREAD

**Issue by Studio384** [ChangeWindows/Viv#32]
This is an issue regarding the entire editor experience in viv. The various points mentioned in this issue may get their own tickets and the scope of this issue isn't limited to ChangeWindows 5.0. Some if this may be tackled in a future update (be it 5.1 or 5.2, heck, might as well be 6.0).

# Current situation
Currently, the editor is a very simple (and very limited) textarea which you can hardly call a proper editor. This is not a good experience to write the ChangeWindows changelogs in.

Navigating in changelogs is currently also rather painful. We currently have a UI where all platforms are listed on the right and the main page shows a - way to spacious - list of all builds that fit in the very limited filters. We shouldn't focus as much on filters as on improving this UI.

# Expected situation
## Overview experience
- [x] **Show more info on changelogs**: we have a `created_on` and `updated_on` field in the changelogs table. Put them to some good use and show this information.
- [x] **Change sort order to last updated**: we currently sort the changelogs on their build number but since lower build nummers can be released (like cumulative updates) this is a bad way to sort things. We should sort by the date they were last updated at.
- [x] **Add "All" filter**: once you navigate to a specific platform, we don't provide a UI to return back to all changelogs.

## Editor
- [x] **Markdown Editor**: we've always written our markdown in Visual Studio Code and moving to a plain old `<textarea>` is kinda a downgrade.

## Others
- [x] #43 **Provide quick create**: when a build does not have a changelog, editors should see a link to create a changelog where its changelog should be. This should fill in the basic information for that changelog by default like build and platform.
- [x] **Move "This is a recent log"**: the recent log warning could be moved out of the changelog's content and bu shown for logs created within the last 24 hours.
