### ISSUE TITLE
Changelog UX 5.1

### ISSUE THREAD

**Issue by Studio384** [ChangeWindows/Viv#57]
## Overview experience
- [ ] **Include vNext**: we should provide easy access to the vNext changelogs from the main changelogs UI. These are 2 separate systems, but a combined editor space would be useful.

## Editor
- [ ] **Templates**: each platform has its own default empty changelog. We currently have to copy and paste this for every new changelog. This should be manageable on ChangeWindows and ChangeWindows should be capable of inserting these templates by itself.

## Version control and tracking
- [ ] **Version management**: we should store previous versions of a changelog to provide ourselves with the capability of reversing to a previous version. Perhaps even see diffs between multiple versions of the same changelog.
- [ ] **Track user**: keep track of who last edited a changelog, this too should be tracked in the version control.
