### ISSUE TITLE
Alpha 1 preparations

### ISSUE THREAD

**Issue by Studio384** [ChangeWindows/Viv#6]
A number of requirements have to be met before ChangeWindows 5.0 alpha 1 can go online to the public.

- [x] **Basic CW functionality**: show a timeline of releases, show changelogs.
- [x] **Basic profile support**: provide basic profiles for people to make an account, allow promotion (for Patrons).
- [x] **Update login/register/reset flow**: they use an empty design, show some care.
- [x] **Subdomain**: prepare our new subdomain to show viv.
- [x] **ChangeWindows 4.12**: prepare ChangeWindows 4 to support the ChangeWindows 5 database.
  - [x] Use the releases table to pull the timeline data from.
  - [x] Use the milestones table to pull the milestone data from.
  - [ ] Use the changelogs table to pull the changelog data from.
- [x] #2 **ChangeWindows Preview App**: submit version ~0.6.1~ 0.6.2 to the Microsoft Store for release.
- [x] **ChangeWindows 4.12.0 announcement**
- [x] **ChangeWindows 5.0-alpha.1 announcement**
